server:
  port: 80
spring:
  application:
    name: simplified-psp
  datasource:
    url: jdbc:mysql://localhost:3306/sps_database?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
